"""empty message

Revision ID: 1a152c7b1378
Revises: ab9053a8983a
Create Date: 2021-12-14 16:20:26.937950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a152c7b1378'
down_revision = 'ab9053a8983a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('steps', sa.String(length=500), nullable=True))
    op.drop_column('task', 'subtasks')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('subtasks', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('task', 'steps')
    # ### end Alembic commands ###
