"""empty message

Revision ID: 1b0a78cce45f
Revises: da50ffe57ce5
Create Date: 2021-12-10 10:17:02.703483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0a78cce45f'
down_revision = 'da50ffe57ce5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_task_is_active'), 'task', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_is_active'), table_name='task')
    op.drop_column('task', 'is_active')
    # ### end Alembic commands ###
