"""empty message

Revision ID: 60989a26e0c4
Revises: ab97cab50316
Create Date: 2021-12-12 11:11:51.268345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60989a26e0c4'
down_revision = 'ab97cab50316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_completed', sa.Boolean(), nullable=True))
    op.add_column('task', sa.Column('times_attempted', sa.Integer(), nullable=True))
    op.add_column('task', sa.Column('times_completed', sa.Integer(), nullable=True))
    op.drop_index('ix_task_is_active', table_name='task')
    op.create_index(op.f('ix_task_times_attempted'), 'task', ['times_attempted'], unique=False)
    op.create_index(op.f('ix_task_times_completed'), 'task', ['times_completed'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_times_completed'), table_name='task')
    op.drop_index(op.f('ix_task_times_attempted'), table_name='task')
    op.create_index('ix_task_is_active', 'task', ['is_active'], unique=False)
    op.drop_column('task', 'times_completed')
    op.drop_column('task', 'times_attempted')
    op.drop_column('task', 'is_completed')
    # ### end Alembic commands ###
