"""empty message

Revision ID: ab9053a8983a
Revises: d22467bc4180
Create Date: 2021-12-14 16:00:04.230401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab9053a8983a'
down_revision = 'd22467bc4180'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('color', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'color')
    # ### end Alembic commands ###
