"""empty message

Revision ID: ccd7b2e52608
Revises: 1b0a78cce45f
Create Date: 2021-12-11 09:59:18.704049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccd7b2e52608'
down_revision = '1b0a78cce45f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_started', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_started')
    # ### end Alembic commands ###
