"""empty message

Revision ID: d22467bc4180
Revises: 60989a26e0c4
Create Date: 2021-12-13 10:40:14.209539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd22467bc4180'
down_revision = '60989a26e0c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_bonus', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'is_bonus')
    # ### end Alembic commands ###
