"""empty message

Revision ID: da50ffe57ce5
Revises: 7897b2436ce9
Create Date: 2021-12-09 09:36:18.872895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da50ffe57ce5'
down_revision = '7897b2436ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.drop_index('ix_task_public', table_name='task')
    op.create_index(op.f('ix_task_is_public'), 'task', ['is_public'], unique=False)
    op.drop_column('task', 'public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('public', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_task_is_public'), table_name='task')
    op.create_index('ix_task_public', 'task', ['public'], unique=False)
    op.drop_column('task', 'is_public')
    # ### end Alembic commands ###
